const express = require('express')
const bodyParser = require('body-parser')
const app = express()
const PORT = process.env.PORT || 5000
const db = require('./queries')

app
    .use(bodyParser.json())
    .use(bodyParser.urlencoded({ extended: true }))
    .get('/', (req, res) => res.json({ info: 'ASP-F1-API' }))
    .get('/circuits', db.getCircuits)
    .get('/circuits/:id', db.getCircuitById)
    .get('/seasons', db.getSeasons)
    .get('/seasons/:year', db.getSeasonByYear)
    .get('/constructors', db.getConstructors)
    .get('/constructors/:id', db.getConstructorById)
    .get('/constructors/:name', db.getConstructorByName)
    .get('/drivers', db.getDrivers)
    .get('/drivers/:id', db.getDriverById)
    .get('/drivers/:name', db.getDriverByName)
    .listen(PORT, () => console.log(`Listening on port ${ PORT }`))
